// Mocks generated by Mockito 5.0.10 from annotations
// in tatsam_app_experimental/test/core/app-page-status/data/repository/app-page-status-repository-impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsam_app_experimental/core/app-page-status/data/models/app-route-model.dart'
    as _i2;
import 'package:tatsam_app_experimental/core/app-page-status/data/sources/app-page-status-local-data-source.dart'
    as _i3;
import 'package:tatsam_app_experimental/features/hub/data/models/hub-status-model.dart'
    as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeAppRouteModel extends _i1.Fake implements _i2.AppRouteModel {}

/// A class which mocks [AppPageStatusLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppPageStatusLocalDataSource extends _i1.Mock
    implements _i3.AppPageStatusLocalDataSource {
  MockAppPageStatusLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AppRouteModel> getLastAbandonedPage(
          {_i5.HubStatusModel? hubStatusModel}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getLastAbandonedPage, [], {#hubStatusModel: hubStatusModel}),
              returnValue:
                  Future<_i2.AppRouteModel>.value(_FakeAppRouteModel()))
          as _i4.Future<_i2.AppRouteModel>);
}
