// Mocks generated by Mockito 5.0.10 from annotations
// in tatsam_app_experimental/test/features/profile-screen/data/repositories/profile-details-repository-impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsam_app_experimental/core/platform/network_info.dart' as _i8;
import 'package:tatsam_app_experimental/features/hub/data/models/hub-status-model.dart'
    as _i3;
import 'package:tatsam_app_experimental/features/profile-screen/data/models/profile-data-model.dart'
    as _i2;
import 'package:tatsam_app_experimental/features/profile-screen/data/models/question-log-model.dart'
    as _i7;
import 'package:tatsam_app_experimental/features/profile-screen/data/sources/profile-details-remote-data-source.dart'
    as _i4;
import 'package:tatsam_app_experimental/features/rapport-building/data/models/mood-tracking-model.dart'
    as _i6;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeProfileDataModel extends _i1.Fake implements _i2.ProfileDataModel {}

class _FakeHubStatusModel extends _i1.Fake implements _i3.HubStatusModel {}

/// A class which mocks [ProfileDetailsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileDetailsRemoteDataSource extends _i1.Mock
    implements _i4.ProfileDetailsRemoteDataSource {
  MockProfileDetailsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ProfileDataModel> getBasicProfileDetails() =>
      (super.noSuchMethod(Invocation.method(#getBasicProfileDetails, []),
              returnValue:
                  Future<_i2.ProfileDataModel>.value(_FakeProfileDataModel()))
          as _i5.Future<_i2.ProfileDataModel>);
  @override
  _i5.Future<_i3.HubStatusModel> getProfileWheelOfLifeData() =>
      (super.noSuchMethod(Invocation.method(#getProfileWheelOfLifeData, []),
              returnValue:
                  Future<_i3.HubStatusModel>.value(_FakeHubStatusModel()))
          as _i5.Future<_i3.HubStatusModel>);
  @override
  _i5.Future<List<_i6.MoodTrackingModel>> getMoodLogs() =>
      (super.noSuchMethod(Invocation.method(#getMoodLogs, []),
              returnValue: Future<List<_i6.MoodTrackingModel>>.value(
                  <_i6.MoodTrackingModel>[]))
          as _i5.Future<List<_i6.MoodTrackingModel>>);
  @override
  _i5.Future<List<_i7.QuestionLogModel>> getProfileQuestions() =>
      (super.noSuchMethod(Invocation.method(#getProfileQuestions, []),
              returnValue: Future<List<_i7.QuestionLogModel>>.value(
                  <_i7.QuestionLogModel>[]))
          as _i5.Future<List<_i7.QuestionLogModel>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i8.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
}
