include: package:lint/analysis_options.yaml
linter:
  rules:
    file_names: false
    avoid_classes_with_only_static_members : false
    non_constant_identifier_names : false
    constant_identifier_names : false
    avoid_function_literals_in_foreach_calls : false
    sort_pub_dependencies : false