name: tatsam_app_experimental
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+27

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_size_and_fade: ^2.0.0
  animations: ^2.0.0
  animator: ^3.1.0
  app_settings: ^4.1.1
  carousel_slider: ^4.0.0
  cross_connectivity: ^3.0.3
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.1
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  flavor: ^1.0.1
  flip_card: ^0.5.0
  flutter_appauth: ^1.0.0+1
  flutter_secure_storage: ^4.2.0
  flutter_sound_lite: ^8.1.4
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  get: ^4.1.4
  get_it: ^6.0.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  image_gallery_saver: ^1.6.9
  onesignal_flutter: ^3.0.0
  page_transition: ^2.0.2
  path_provider: ^2.0.2
  permission_handler: ^8.1.1
  platform_device_id: ^1.0.1
  responsive_builder: ^0.4.1
  rxdart: ^0.27.1
  shimmer: ^2.0.0
  simple_animations: ^3.1.1
  smartlook: ^2.0.1
  syncfusion_flutter_charts: ^19.1.69+1
  url_launcher: ^6.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  hive_generator: ^1.1.0
  lint: ^1.5.3
  mockito: ^5.0.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/Rapport-screen/
    - assets/path/
    - assets/profile-icon/
    - assets/path/guided-path/
    - assets/path/guided-path/day 1/
    - assets/path/guided-path/select-option/
    - assets/path/self-driven-path/
    - assets/path/self-driven-path/select-option/
    - assets/path/self-driven-path/mental/
    - assets/Rapport-screen/images/
    - assets/translations/
    - assets/universal_images/
    - assets/opening-screen/
    - assets/onboarding-incomplete/
    - assets/choose-path-screen/
    - assets/hub/
    - assets/Rapport_light_image/
    - assets/focus-screen/
    - assets/returning-user-screen/
    - assets/opening-screen/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
