// Mocks generated by Mockito 5.0.10 from annotations
// in tatsam_app_experimental/test/features/hub/repository/create-traveller-service-impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsam_app_experimental/core/platform/network_info.dart' as _i5;
import 'package:tatsam_app_experimental/features/hub/data/sources/create-traveller-remote-service.dart'
    as _i3;
import 'package:tatsam_app_experimental/features/hub/domain/entities/success-create-traveller.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeSuccessCreatedTraveller extends _i1.Fake
    implements _i2.SuccessCreatedTraveller {}

/// A class which mocks [CreateTravellerRemoteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateTravellerRemoteService extends _i1.Mock
    implements _i3.CreateTravellerRemoteService {
  MockCreateTravellerRemoteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SuccessCreatedTraveller> createTraveller() =>
      (super.noSuchMethod(Invocation.method(#createTraveller, []),
              returnValue: Future<_i2.SuccessCreatedTraveller>.value(
                  _FakeSuccessCreatedTraveller()))
          as _i4.Future<_i2.SuccessCreatedTraveller>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}
