// Mocks generated by Mockito 5.0.10 from annotations
// in tatsam_app_experimental/test/features/hub/repository/get-hub-status-repository-impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsam_app_experimental/core/platform/network_info.dart' as _i5;
import 'package:tatsam_app_experimental/features/hub/data/models/hub-status-model.dart'
    as _i2;
import 'package:tatsam_app_experimental/features/hub/data/sources/get-hub-status-remote-data-source.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeHubStatusModel extends _i1.Fake implements _i2.HubStatusModel {}

/// A class which mocks [GetHubStatusRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHubStatusRemoteDataSource extends _i1.Mock
    implements _i3.GetHubStatusRemoteDataSource {
  MockGetHubStatusRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HubStatusModel> getHubStatus() => (super.noSuchMethod(
          Invocation.method(#getHubStatus, []),
          returnValue: Future<_i2.HubStatusModel>.value(_FakeHubStatusModel()))
      as _i4.Future<_i2.HubStatusModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}
