// Mocks generated by Mockito 5.0.10 from annotations
// in tatsam_app_experimental/test/core/duration-tracker/domain/usecases/get-last-login_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsam_app_experimental/core/duration-tracker/domain/entities/app-duration.dart'
    as _i6;
import 'package:tatsam_app_experimental/core/duration-tracker/domain/repository/app-duration-repository.dart'
    as _i3;
import 'package:tatsam_app_experimental/core/error/failures.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {
  @override
  String toString() => super.toString();
}

/// A class which mocks [AppDurationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDurationRepository extends _i1.Mock
    implements _i3.AppDurationRepository {
  MockAppDurationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> updateUserDurationOnApp(
          {_i6.AppDuration? appDuration, bool? isNewUser}) =>
      (super.noSuchMethod(
              Invocation.method(#updateUserDurationOnApp, [],
                  {#appDuration: appDuration, #isNewUser: isNewUser}),
              returnValue: Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                  _FakeEither<_i5.Failure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AppDuration>> getLastLogin() =>
      (super.noSuchMethod(Invocation.method(#getLastLogin, []),
          returnValue: Future<_i2.Either<_i5.Failure, _i6.AppDuration>>.value(
              _FakeEither<_i5.Failure, _i6.AppDuration>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.AppDuration>>);
}
