// Mocks generated by Mockito 5.0.10 from annotations
// in tatsam_app_experimental/test/features/what-path-to-choose/domain/usecases/get-journey-path-list_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsam_app_experimental/core/error/failures.dart' as _i5;
import 'package:tatsam_app_experimental/core/success/success-interface.dart'
    as _i7;
import 'package:tatsam_app_experimental/features/what-path-to-choose/domain/entites/journey.dart'
    as _i6;
import 'package:tatsam_app_experimental/features/what-path-to-choose/domain/repositories/path-operations-repository.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [PathOperationsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPathOperationsRepository extends _i1.Mock
    implements _i2.PathOperationsRepository {
  MockPathOperationsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Journey>>?> getJourneyPaths() =>
      (super.noSuchMethod(Invocation.method(#getJourneyPaths, []),
              returnValue:
                  Future<_i4.Either<_i5.Failure, List<_i6.Journey>>?>.value())
          as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Journey>>?>);
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i7.Success>?> startJourney(
          {_i6.Journey? journey}) =>
      (super.noSuchMethod(
              Invocation.method(#startJourney, [], {#journey: journey}),
              returnValue:
                  Future<_i4.Either<_i5.Failure, _i7.Success>?>.value())
          as _i3.Future<_i4.Either<_i5.Failure, _i7.Success>?>);
}
