// Mocks generated by Mockito 5.0.10 from annotations
// in tatsam_app_experimental/test/core/activity-manager/data/repositories/update-activity-status-service-impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsam_app_experimental/core/activity-management/data/models/activity-status-model.dart'
    as _i2;
import 'package:tatsam_app_experimental/core/activity-management/data/sources/update-activity-status-remote-sevice.dart'
    as _i3;
import 'package:tatsam_app_experimental/core/platform/network_info.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeActivityStatusModel extends _i1.Fake
    implements _i2.ActivityStatusModel {}

/// A class which mocks [UpdateActivityStatusRemoteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateActivityStatusRemoteService extends _i1.Mock
    implements _i3.UpdateActivityStatusRemoteService {
  MockUpdateActivityStatusRemoteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ActivityStatusModel> modifyStatus(
          {String? status, int? actionId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #modifyStatus, [], {#status: status, #actionId: actionId}),
              returnValue: Future<_i2.ActivityStatusModel>.value(
                  _FakeActivityStatusModel()))
          as _i4.Future<_i2.ActivityStatusModel>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}
