// Mocks generated by Mockito 5.0.10 from annotations
// in tatsam_app_experimental/test/features/profile-screen/domain/usecases/get-mood-logs_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsam_app_experimental/core/error/failures.dart' as _i5;
import 'package:tatsam_app_experimental/features/hub/domain/entities/hub-status.dart'
    as _i7;
import 'package:tatsam_app_experimental/features/profile-screen/domain/entities/profile-data.dart'
    as _i6;
import 'package:tatsam_app_experimental/features/profile-screen/domain/entities/question-log.dart'
    as _i9;
import 'package:tatsam_app_experimental/features/profile-screen/domain/repositories/profile-details-repository.dart'
    as _i2;
import 'package:tatsam_app_experimental/features/rapport-building/domain/entities/mood-tracking.dart'
    as _i8;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ProfileDetailsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileDetailsRepository extends _i1.Mock
    implements _i2.ProfileDetailsRepository {
  MockProfileDetailsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileData>?>
      getBasicProfileDetails() =>
          (super.noSuchMethod(Invocation.method(#getBasicProfileDetails, []),
                  returnValue:
                      Future<_i4.Either<_i5.Failure, _i6.ProfileData>?>.value())
              as _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileData>?>);
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i7.HubStatus>?>
      getProfileWheelOfLifeData() =>
          (super.noSuchMethod(Invocation.method(#getProfileWheelOfLifeData, []),
                  returnValue:
                      Future<_i4.Either<_i5.Failure, _i7.HubStatus>?>.value())
              as _i3.Future<_i4.Either<_i5.Failure, _i7.HubStatus>?>);
  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.MoodTracking>>?> getMoodLogs() =>
      (super.noSuchMethod(Invocation.method(#getMoodLogs, []),
              returnValue: Future<
                  _i4.Either<_i5.Failure, List<_i8.MoodTracking>>?>.value())
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.MoodTracking>>?>);
  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.QuestionLog>>?>
      getProfileQuestions() =>
          (super.noSuchMethod(Invocation.method(#getProfileQuestions, []),
                  returnValue: Future<
                      _i4.Either<_i5.Failure, List<_i9.QuestionLog>>?>.value())
              as _i3.Future<_i4.Either<_i5.Failure, List<_i9.QuestionLog>>?>);
}
