// Mocks generated by Mockito 5.0.10 from annotations
// in tatsam_app_experimental/test/core/cache-management/data/repositories/log-last-opened-app-service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsam_app_experimental/core/cache-manager/data/services/app-last-opened-log-service.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeUnit extends _i1.Fake implements _i2.Unit {
  @override
  String toString() => super.toString();
}

class _FakeDateTime extends _i1.Fake implements DateTime {
  @override
  String toString() => super.toString();
}

/// A class which mocks [AppLastOpenedLogLocalService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLastOpenedLogLocalService extends _i1.Mock
    implements _i3.AppLastOpenedLogLocalService {
  MockAppLastOpenedLogLocalService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Unit> logStartDatetime() =>
      (super.noSuchMethod(Invocation.method(#logStartDatetime, []),
              returnValue: Future<_i2.Unit>.value(_FakeUnit()))
          as _i4.Future<_i2.Unit>);
  @override
  _i4.Future<DateTime> retrieveLastLog() =>
      (super.noSuchMethod(Invocation.method(#retrieveLastLog, []),
              returnValue: Future<DateTime>.value(_FakeDateTime()))
          as _i4.Future<DateTime>);
}
