// Mocks generated by Mockito 5.0.10 from annotations
// in tatsam_app_experimental/test/core/cache-management/data/repositories/retrieve-most-recent-activity-repository-impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsam_app_experimental/core/cache-manager/data/models/cache-acitivity-model.dart'
    as _i2;
import 'package:tatsam_app_experimental/core/cache-manager/data/services/retrieve-most-recent-activity-local-data-source.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeCacheAcitivityModel extends _i1.Fake
    implements _i2.CacheAcitivityModel {}

/// A class which mocks [RetrieveMostRecentActivityLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRetrieveMostRecentActivityLocalDataSource extends _i1.Mock
    implements _i3.RetrieveMostRecentActivityLocalDataSource {
  MockRetrieveMostRecentActivityLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CacheAcitivityModel> retrieveActivity() => (super.noSuchMethod(
          Invocation.method(#retrieveActivity, []),
          returnValue:
              Future<_i2.CacheAcitivityModel>.value(_FakeCacheAcitivityModel()))
      as _i4.Future<_i2.CacheAcitivityModel>);
}
