// Mocks generated by Mockito 5.0.10 from annotations
// in tatsam_app_experimental/test/features/home-management/domain/usecases/add-weekly-activity_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsam_app_experimental/core/activity/domain/entities/recommendation-category.dart'
    as _i6;
import 'package:tatsam_app_experimental/core/error/failures.dart' as _i5;
import 'package:tatsam_app_experimental/features/home-management/domain/repositories/add-weekly-category-service.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [AddWeeklyCategoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddWeeklyCategoryService extends _i1.Mock
    implements _i2.AddWeeklyCategoryService {
  MockAddWeeklyCategoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>?> addWeeklyCategory(
          {int? weekNumber, _i6.RecommendationCategory? category}) =>
      (super.noSuchMethod(
              Invocation.method(#addWeeklyCategory, [],
                  {#weekNumber: weekNumber, #category: category}),
              returnValue: Future<_i4.Either<_i5.Failure, _i4.Unit>?>.value())
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>?>);
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>?> addWeeklyActivity(
          {String? category, String? recommendationId}) =>
      (super.noSuchMethod(
              Invocation.method(#addWeeklyActivity, [],
                  {#category: category, #recommendationId: recommendationId}),
              returnValue: Future<_i4.Either<_i5.Failure, _i4.Unit>?>.value())
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>?>);
}
