// Mocks generated by Mockito 5.0.10 from annotations
// in tatsam_app_experimental/test/core/cache-management/domain/usecases/log-app-start-time_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsam_app_experimental/core/cache-manager/domain/repositories/log-last-opened-app-service.dart'
    as _i2;
import 'package:tatsam_app_experimental/core/error/failures.dart' as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [LogLastOpenedAppService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogLastOpenedAppService extends _i1.Mock
    implements _i2.LogLastOpenedAppService {
  MockLogLastOpenedAppService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>?> logStartDatetime() =>
      (super.noSuchMethod(Invocation.method(#logStartDatetime, []),
              returnValue: Future<_i4.Either<_i5.Failure, _i4.Unit>?>.value())
          as _i3.Future<_i4.Either<_i5.Failure, _i4.Unit>?>);
  @override
  _i3.Future<_i4.Either<_i5.Failure, DateTime>?> retrieveLastLog() =>
      (super.noSuchMethod(Invocation.method(#retrieveLastLog, []),
              returnValue: Future<_i4.Either<_i5.Failure, DateTime>?>.value())
          as _i3.Future<_i4.Either<_i5.Failure, DateTime>?>);
}
