// Mocks generated by Mockito 5.0.10 from annotations
// in tatsam_app_experimental/test/core/duration-tracker/data/repositories/app-duration-repository-impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tatsam_app_experimental/core/duration-tracker/data/models/app-duration-model.dart'
    as _i3;
import 'package:tatsam_app_experimental/core/duration-tracker/data/sources/app-duration-local-data-source.dart'
    as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeUnit extends _i1.Fake implements _i2.Unit {
  @override
  String toString() => super.toString();
}

class _FakeAppDurationModel extends _i1.Fake implements _i3.AppDurationModel {}

/// A class which mocks [AppDurationLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDurationLocalDataSource extends _i1.Mock
    implements _i4.AppDurationLocalDataSource {
  MockAppDurationLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Unit> updateUserDurationOnApp(
          {_i3.AppDurationModel? appDuration, bool? isNewUser}) =>
      (super.noSuchMethod(
              Invocation.method(#updateUserDurationOnApp, [],
                  {#appDuration: appDuration, #isNewUser: isNewUser}),
              returnValue: Future<_i2.Unit>.value(_FakeUnit()))
          as _i5.Future<_i2.Unit>);
  @override
  _i5.Future<_i3.AppDurationModel> getLastLogin() =>
      (super.noSuchMethod(Invocation.method(#getLastLogin, []),
              returnValue:
                  Future<_i3.AppDurationModel>.value(_FakeAppDurationModel()))
          as _i5.Future<_i3.AppDurationModel>);
}
